name: Java CI with Maven

on:
  push:
    # branches: [ main ]
  pull_request:
    # branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

          # Generate HTML report for Snyk Code
      - name: install snyk-to-html
        run: |
        
               npm install snyk-to-html -g
               # Convert JSON output from `snyk test --json` into a static HTML
               snyk code test --json | snyk-to-html -o code-result.html
               mkdir downloads
               cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: run MVN install
        run: mvn install # install maven

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install snyk -g # install snyk
      - run: snyk -v
      - run: snyk config set endpoint=${{ secrets.SNYK_URL}} # Snyk API url set to AU
      - run: snyk auth ${{ secrets.SNYK_TOKEN }} # snyk authentication using GH secrets
              # Generate the HTML report
      - name: install snyk-to-html
        run: |
        
               npm install snyk-to-html -g
               # Convert JSON output from `snyk test --json` into a static HTML
               snyk test --json | snyk-to-html -o result.html
               mkdir downloads
               cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

      # save the HTML in the artifact
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: downloads

      # Add the artifact to Jira issues
      # - name: Download snyk-jira-sync-linux 
      #   uses: actions/download-artifact@v3 
      #   with: 
      #     name: snyk-jira-sync 
      # # Match the artifact name uploaded during release process 
      # - name: Make executable 
      # - run: chmod +x snyk-jira-sync-linux 
      # - name: Run snyk-jira-sync-linux 
      #         # Avoid embedding sensitive credentials directly in the workflow 
      #         # Use secrets or environment variables instead 
      #         env: SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }} SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
      #         run: ./snyk-jira-sync-linux --jiraProjectKey=TEAM_A 
      # - name: Upload snyk-jira-sync logs (optional) 
      #   uses: actions/upload-artifact@v3 
      #   with: 
      #     name: snyk-jira-sync-logs 
      #     path: snyk-jira-sync.log # Replace with your log file path